//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class gcmRegistration
    {
        public long registrationId { get; set; }
        public string deviceRegistrationId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
