//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNTAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCompanyDetail
    {
        public int companyId { get; set; }
        public string companyName { get; set; }
        public string companyDsc { get; set; }
        public Nullable<int> userId { get; set; }
    }
}
